version: "3.3"

services:
  nbk:
    build: .
    volumes:
      - /Users/agostinocalamia/Documents/da_vinci:/app
    networks:
      - da_vinci
    environment:
      - JUPYTER_ENABLE_LAB:"yes"
    ports:
      - "0.0.0.0:8888:8888"
    entrypoint: ["jupyter", "lab", "--ip=0.0.0.0", "--allow-root"]

networks:
  da_vinci:
