column_names:
  [
    "product",
    "land_use_chage",
    "animal_feed",
    "farm",
    "processing",
    "transport",
    "packaging",
    "retail",
  ]
data_dir: data
ghg_data_file_name: ghg_data.csv
image_height: 224
image_width: 224
food_weight_file_name: food_weight_data.csv
model_dir: saved_models
model_name: retrained_mobilenet
module_handle: https://tfhub.dev/google/openimages_v4/ssd/mobilenet_v2/1
environment_variables:
  - env_name: ZERO_ENV
    config_name: section
